# --- Produktion mit GitHub-OAuth ------------
backend:
  name: github
  repo: RapidoX33/demo-static    
  branch: main
  base_url: https://sveltia-cms-auth.netlify.app

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Seiten"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Body",  name: "body",  widget: "markdown" }