# --- Produktion mit GitHub-OAuth ------------
backend:
  name: github
  repo: RapidoX33/demo-static    # GitHub-Repo (User/Reponame)
  branch: main
  auth_type: implicit               # kein extra Server nötig
  client_id: Ov23liDFRkPnp1RJw8TM         # aus GitHub-OAuth-App

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Seiten"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Body",  name: "body",  widget: "markdown" }